### ISSUE TITLE
Fails to build with GHC 9.2.1

### ISSUE THREAD

**Issue by arjunkathuria** [typeable/generic-arbitrary#12]
Hi, 
the package failing to build with GHC 9.2.1

this package is part of dependency in ghcup test suite and it causes it to fail when building/testing with GHC 9.2.1

The Logs :- 

```
Failed to build generic-arbitrary-0.2.0.
Build log (
/home/username/.cabal/logs/ghc-9.2.1/generic-arbitrary-0.2.0-b7ba577fe184c21dde1df651e1a01fd625359d2e2adc1e72a43a5dae766cbcf6.log
):
Warning: generic-arbitrary.cabal:18:28: Packages with 'cabal-version: 1.12' or
later should specify a specific version of the Cabal spec of the form
'cabal-version: x.y'. Use 'cabal-version: 1.22'.
Configuring library for generic-arbitrary-0.2.0..
Preprocessing library for generic-arbitrary-0.2.0..
Building library for generic-arbitrary-0.2.0..
[1 of 1] Compiling Test.QuickCheck.Arbitrary.Generic ( src/Test/QuickCheck/Arbitrary/Generic.hs, dist/build/Test/QuickCheck/Arbitrary/Generic.o, dist/build/Test/QuickCheck/Arbitrary/Generic.dyn_o )

src/Test/QuickCheck/Arbitrary/Generic.hs:53:3: error:
    • Non type-variable argument in the constraint: GArbitrary (Rep a)
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘Arbitrary (GenericArbitrary a)’
   |
53 |   ( Generic a,
   |   ^^^^^^^^^^^^...

src/Test/QuickCheck/Arbitrary/Generic.hs:82:10: error:
    • Non type-variable argument in the constraint: KnownNat (SumLen a)
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘GArbitrary (a :+: b)’
   |
82 | instance (GArbitrary a, GArbitrary b, KnownNat (SumLen a), KnownNat (SumLen b)
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build generic-arbitrary-0.2.0 (which is required by
test:ghcup-test from ghcup-0.1.17.4). See the build log above for details.
```

**Comment by pbrisbin** [comment]
It looks like the referencing PR has fixed this issue a few months ago. Can we get a release on Hackage?

9.2 has made it into Stackage nightly, so this is blocking a number of our packages from staying.

**Comment by ilyakooo0** [comment]
@pbrisbin Thanks for pointing it out. We will create a new release soon.

**Comment by ilyakooo0** [comment]
[hackage.haskell.org/package/generic-arbitrary-0.2.1 ](https://hackage.haskell.org/package/generic-arbitrary-0.2.1)
